plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.7'

	id 'com.diffplug.spotless' version '6.25.0'
}


group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'back-end for picknwhip'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.15'
    // Spatial 기능 추가 (Point 타입 사용을 위해)
    implementation 'org.hibernate.orm:hibernate-spatial'
	runtimeOnly 'com.h2database:h2'
}

tasks.named('test') {
	useJUnitPlatform()
}

spotless {
	java {
		// Google Java Format 적용
		googleJavaFormat()
		removeUnusedImports()
		trimTrailingWhitespace()
		endWithNewline()
	}
}


//git hook 설정(spotlessApply 자동화)
tasks.register('updateGitHooks', Copy) {
	from new File(rootProject.rootDir, '.github/hooks/pre-commit')

	into { new File(rootProject.rootDir, '.git/hooks') }
	fileMode 0775
}

tasks.named('compileJava') {
	dependsOn 'spotlessApply'  // 컴파일 시 포맷팅 자동 적용
	dependsOn 'updateGitHooks' // 컴파일 시 훅 파일 최신화
}

// 기본 test는 mysql 태그 제외 + mysqlTest 태스크 추가
tasks.test {
    useJUnitPlatform {
        excludeTags "mysql"
    }
}

tasks.register("mysqlTest", Test) {
    useJUnitPlatform {
        includeTags "mysql"
    }
}