app:
  cookie-domain: ""  # 로컬에서는 domain 미설정 (localhost 기준)

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"

kakao:
  rest-api-key: ${KAKAO_CLIENT_ID}

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
