-- V1__init.sql
-- Pick&Whip baseline schema (MySQL / Flyway)
-- NOTE:
--  - This file is an "init snapshot" that already includes the V1_1_0 refactor:
--    * custom_options.color_rgb_code is NULLable
--    * design_options.custom_id -> custom_option_id (with stable FK name)
--    * order_draft_items.custom_id removed
--    * order_items.custom_id -> custom_option_id, color_rgb_code NULLable (with stable FK name)
--    * report table includes status/answer/processed_at
--
-- After this version is merged, DO NOT edit this file again.
-- Any schema changes must be applied via a NEW migration (e.g. V2__*.sql).

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `bank_accounts` (
                                 `bank_account_id` bigint NOT NULL AUTO_INCREMENT,
                                 `account_holder` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                                 `account_number` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                                 `bank_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                                 `is_primary` tinyint(1) DEFAULT '0',
                                 `shop_id` bigint DEFAULT NULL,
                                 PRIMARY KEY (`bank_account_id`),
                                 KEY `FKt6t7oiuxdwfcu798ik0kmkcb2` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `chat_messages` (
                                 `chat_id` bigint NOT NULL AUTO_INCREMENT,
                                 `created_at` datetime(6) NOT NULL,
                                 `updated_at` datetime(6) NOT NULL,
                                 `is_read` bit(1) NOT NULL,
                                 `message_image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                 `message_text` text COLLATE utf8mb4_unicode_ci,
                                 `message_type` enum('IMAGE','TEXT') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                 `room_id` bigint DEFAULT NULL,
                                 `sender_id` bigint DEFAULT NULL,
                                 PRIMARY KEY (`chat_id`),
                                 KEY `FKhalwepod3944695ji0suwoqb9` (`room_id`),
                                 KEY `FKgiqeap8ays4lf684x7m0r2729` (`sender_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `chat_rooms` (
                              `chat_room_id` bigint NOT NULL AUTO_INCREMENT,
                              `created_at` datetime(6) NOT NULL,
                              `updated_at` datetime(6) NOT NULL,
                              `last_message_id` bigint DEFAULT NULL,
                              `customer_id` bigint DEFAULT NULL,
                              `shop_id` bigint DEFAULT NULL,
                              PRIMARY KEY (`chat_room_id`),
                              KEY `FK42l1eff8qlbln1331stm3ml2h` (`customer_id`),
                              KEY `FKtqhifsbloj4e5rlyobaljrx3f` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `custom_options` (
                                  `id` bigint NOT NULL AUTO_INCREMENT,
                                  `additional_price` int NOT NULL,
                                  `category` enum('CREAM','ICING','LETTERING','PEN','SHAPE','SHEET','TOPPING') COLLATE utf8mb4_unicode_ci NOT NULL,
                                  `color_rgb_code` varchar(7) COLLATE utf8mb4_unicode_ci NULL,
                                  `option_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                  `shop_id` bigint DEFAULT NULL,
                                  PRIMARY KEY (`id`),
                                  KEY `FKrugbtewrcp0p4u6d935gtphmc` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `design_gallery` (
                                  `id` bigint NOT NULL AUTO_INCREMENT,
                                  `allergy_info` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                  `base_price` int NOT NULL,
                                  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                  `design_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                                  `image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `design_options` (
                                  `id` bigint NOT NULL AUTO_INCREMENT,
                                  `custom_option_id` bigint NOT NULL,
                                  `design_id` bigint NOT NULL,
                                  PRIMARY KEY (`id`),
                                  KEY `idx_design_options_custom_option_id` (`custom_option_id`),
                                  KEY `FKmohfd3bekh421w305mehsfxj` (`design_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `favorite_shops` (
                                  `id` bigint NOT NULL AUTO_INCREMENT,
                                  `created_at` datetime(6) NOT NULL,
                                  `shop_id` bigint DEFAULT NULL,
                                  `user_id` bigint DEFAULT NULL,
                                  PRIMARY KEY (`id`),
                                  KEY `FK7m5h5jy7wn8pqae5hhbhnipgb` (`shop_id`),
                                  KEY `FKec6hcwwd5t15ojqqcoyfp1q3h` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notification` (
                                `id` bigint NOT NULL AUTO_INCREMENT,
                                `created_at` datetime(6) NOT NULL,
                                `updated_at` datetime(6) NOT NULL,
                                `content` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
                                `is_read` bit(1) NOT NULL,
                                `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
                                `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                                PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_draft_items` (
                                     `id` bigint NOT NULL AUTO_INCREMENT,
                                     `position_x` double DEFAULT NULL,
                                     `position_y` double DEFAULT NULL,
                                     `custom_option_id` bigint NOT NULL,
                                     `draft_id` bigint NOT NULL,
                                     PRIMARY KEY (`id`),
                                     KEY `FKq82jflsxitmkpt4yshjhhh3m9` (`custom_option_id`),
                                     KEY `FKih52bdbg2e9tdofv6hvif54gl` (`draft_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_items` (
                               `id` bigint NOT NULL AUTO_INCREMENT,
                               `color_rgb_code` varchar(7) COLLATE utf8mb4_unicode_ci NULL,
                               `option_category` enum('CREAM','ICING','LETTERING','PEN','SHAPE','SHEET','TOPPING') COLLATE utf8mb4_unicode_ci NOT NULL,
                               `option_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                               `unit_price` int NOT NULL,
                               `position_x` double DEFAULT NULL,
                               `position_y` double DEFAULT NULL,
                               `custom_option_id` bigint NOT NULL,
                               `order_id` bigint NOT NULL,
                               PRIMARY KEY (`id`),
                               KEY `idx_order_items_custom_option_id` (`custom_option_id`),
                               KEY `FKbioxgbv59vetrxe0ejfubep1w` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders` (
                          `id` bigint NOT NULL AUTO_INCREMENT,
                          `created_at` datetime(6) NOT NULL,
                          `updated_at` datetime(6) NOT NULL,
                          `additional_request` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                          `deposit_amount` int DEFAULT NULL,
                          `lettering_alignment` enum('CENTER','CURVE_UP','CURVE_UP_DOWN') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                          `lettering_line_count` enum('ONE_LINE','THREE_LINE','TWO_LINE') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                          `lettering_text` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                          `payment_method` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                          `payment_status` enum('CANCELLED','PAID','WAITING') COLLATE utf8mb4_unicode_ci NOT NULL,
                          `pickup_datetime` datetime(6) NOT NULL,
                          `reference_image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                          `rejection_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                          `status` enum('COMPLETED','CONFIRM_WAIT','IMPOSSIBLE','MAKING','PICKUP_WAIT','PROD_CONFIRM') COLLATE utf8mb4_unicode_ci NOT NULL,
                          `total_price` int NOT NULL,
                          `design_id` bigint NOT NULL,
                          `shop_id` bigint NOT NULL,
                          `shop_cake_size_id` bigint NOT NULL,
                          `user_id` bigint NOT NULL,
                          PRIMARY KEY (`id`),
                          KEY `FKiskguoio3bb0nlsy61lwxh7ub` (`design_id`),
                          KEY `FK21gttsw5evi5bbsvleui69d7r` (`shop_id`),
                          KEY `FK48bqo75cycyxtwdef0sbxcx7d` (`shop_cake_size_id`),
                          KEY `FK32ql8ubntj5uh44ph9659tiih` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders_drafts` (
                                 `id` bigint NOT NULL AUTO_INCREMENT,
                                 `created_at` datetime(6) NOT NULL,
                                 `updated_at` datetime(6) NOT NULL,
                                 `additional_request` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                 `lettering_alignment` enum('CENTER','CURVE_UP','CURVE_UP_DOWN') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                 `lettering_line_count` enum('ONE_LINE','THREE_LINE','TWO_LINE') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                 `lettering_text` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                 `pickup_datetime` datetime(6) DEFAULT NULL,
                                 `reference_image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                 `design_id` bigint DEFAULT NULL,
                                 `shop_id` bigint NOT NULL,
                                 `shop_cake_size_id` bigint NOT NULL,
                                 `user_id` bigint NOT NULL,
                                 PRIMARY KEY (`id`),
                                 KEY `FK91tsaqqk9uu8mf5ytymh9qrh1` (`design_id`),
                                 KEY `FK21vvd0w6ny4ndl4sj0yhuggud` (`shop_id`),
                                 KEY `FK7pv0b7rtxy4aa8pfg9olib9oc` (`shop_cake_size_id`),
                                 KEY `FK9b49wh3mdp87r06briy66omq6` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payments` (
                            `payment_id` bigint NOT NULL AUTO_INCREMENT,
                            `approved_at` datetime(6) DEFAULT NULL,
                            `discount_amount` bigint DEFAULT NULL,
                            `payment_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                            `payment_method` enum('CARD','SIMPLE_PAY','TRANSFER','VIRTUAL_ACCOUNT') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                            `receipt_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                            `requested_at` datetime(6) DEFAULT NULL,
                            `status` enum('ABORTED','CANCELED','DONE','PARTIAL_CANCELED','READY') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                            `total_amount` bigint NOT NULL,
                            `order_id` bigint DEFAULT NULL,
                            PRIMARY KEY (`payment_id`),
                            UNIQUE KEY `UK35yqdahtiysne6iij9ske72bj` (`payment_key`),
                            UNIQUE KEY `UK8vo36cen604as7etdfwmyjsxt` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `report` (
                          `report_id` bigint NOT NULL AUTO_INCREMENT,
                          `created_at` datetime(6) NOT NULL,
                          `updated_at` datetime(6) NOT NULL,
                          `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
                          `reason_type` enum('COPYRIGHT_INFRINGEMENT','FALSE_INFORMATION','FRAUD_SUSPECTED','INAPPROPRIATE_CONTENT','OTHER','SPAM_OR_AD') COLLATE utf8mb4_unicode_ci NOT NULL,
                          `target_id` bigint DEFAULT NULL,
                          `target_type` enum('CHAT','REVIEW','SHOP') COLLATE utf8mb4_unicode_ci NOT NULL,
                          `reporter_id` bigint DEFAULT NULL,
                          `status` enum('PENDING','COMPLETED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
                          `answer` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                          `processed_at` datetime(6) DEFAULT NULL,
                          PRIMARY KEY (`report_id`),
                          KEY `FKqbhdxqd3ly7fkhly5nrl2j93k` (`reporter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `review` (
                          `id` bigint NOT NULL AUTO_INCREMENT,
                          `created_at` datetime(6) NOT NULL,
                          `updated_at` datetime(6) NOT NULL,
                          `content` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
                          `deleted_at` datetime(6) DEFAULT NULL,
                          `rating` int NOT NULL,
                          PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `review_image` (
                                `id` bigint NOT NULL AUTO_INCREMENT,
                                `created_at` datetime(6) NOT NULL,
                                `updated_at` datetime(6) NOT NULL,
                                `deleted_at` datetime(6) DEFAULT NULL,
                                `s3_key` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
                                `sort_order` int NOT NULL,
                                `review_id` bigint NOT NULL,
                                `active_sort_order` int GENERATED ALWAYS AS (
                                    CASE WHEN (`deleted_at` IS NULL) THEN `sort_order` ELSE NULL END
                                    ) STORED,
                                PRIMARY KEY (`id`),
                                UNIQUE KEY `uk_review_image_review_active_order` (`review_id`,`active_sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `review_keyword` (
                                  `id` bigint NOT NULL AUTO_INCREMENT,
                                  `keyword` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
                                  `category` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
                                  PRIMARY KEY (`id`),
                                  UNIQUE KEY `uk_review_keyword_category_keyword` (`category`,`keyword`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `review_like` (
                               `id` bigint NOT NULL AUTO_INCREMENT,
                               `created_at` datetime(6) NOT NULL,
                               `updated_at` datetime(6) NOT NULL,
                               `review_id` bigint NOT NULL,
                               PRIMARY KEY (`id`),
                               KEY `FK68am9vk1s1e8n1v873meqkk0k` (`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `review_reply` (
                                `id` bigint NOT NULL AUTO_INCREMENT,
                                `created_at` datetime(6) NOT NULL,
                                `updated_at` datetime(6) NOT NULL,
                                `content` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
                                `deleted_at` datetime(6) DEFAULT NULL,
                                `review_id` bigint NOT NULL,
                                PRIMARY KEY (`id`),
                                UNIQUE KEY `uk_review_reply_review` (`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `review_selected_keyword` (
                                           `id` bigint NOT NULL AUTO_INCREMENT,
                                           `keyword_id` bigint NOT NULL,
                                           `review_id` bigint NOT NULL,
                                           PRIMARY KEY (`id`),
                                           UNIQUE KEY `uk_review_keyword` (`review_id`,`keyword_id`),
                                           KEY `FK62c7uliqny1qxnhvde152141b` (`keyword_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shop_appeal_keywords` (
                                        `keyword_id` bigint NOT NULL AUTO_INCREMENT,
                                        `keyword_text` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                                        `keyword_type` enum('NORMAL','URGENT') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                        PRIMARY KEY (`keyword_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shop_business_hours` (
                                       `id` bigint NOT NULL AUTO_INCREMENT,
                                       `close_time` time(6) DEFAULT NULL,
                                       `date` date DEFAULT NULL,
                                       `day_of_week` int DEFAULT NULL,
                                       `is_closed` tinyint(1) DEFAULT '0',
                                       `open_time` time(6) DEFAULT NULL,
                                       `schedule_type` enum('DATE','WEEKLY') COLLATE utf8mb4_unicode_ci NOT NULL,
                                       `shop_id` bigint DEFAULT NULL,
                                       PRIMARY KEY (`id`),
                                       KEY `FKdktm12aap5yf6c8tmj68dqfkq` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shop_cake_sizes` (
                                   `size_id` bigint NOT NULL AUTO_INCREMENT,
                                   `diameter` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                                   `price` int NOT NULL,
                                   `size_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                                   `shop_id` bigint DEFAULT NULL,
                                   PRIMARY KEY (`size_id`),
                                   KEY `FKsid6g9usj0bjhh7k5sxcnsvto` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shop_events` (
                               `event_id` bigint NOT NULL AUTO_INCREMENT,
                               `content` text COLLATE utf8mb4_unicode_ci,
                               `end_date` date NOT NULL,
                               `is_active` tinyint(1) DEFAULT '1',
                               `start_date` date NOT NULL,
                               `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                               `shop_id` bigint DEFAULT NULL,
                               PRIMARY KEY (`event_id`),
                               KEY `FKt7qu2wqs1y53ofhd9ps8h9s0d` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shop_keyword_mapping` (
                                        `id` bigint NOT NULL AUTO_INCREMENT,
                                        `keyword_id` bigint DEFAULT NULL,
                                        `shop_id` bigint DEFAULT NULL,
                                        PRIMARY KEY (`id`),
                                        KEY `FK8l02mxoj8alsu70ek4flx9mdf` (`keyword_id`),
                                        KEY `FK32jsqya1i9t0bx9lw99vfftks` (`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `shops` (
                         `shop_id` bigint NOT NULL AUTO_INCREMENT,
                         `average_rating` double DEFAULT NULL,
                         `chat_nickname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `chat_profile_image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `created_at` datetime(6) DEFAULT NULL,
                         `day_order_guide` text COLLATE utf8mb4_unicode_ci,
                         `description` text COLLATE utf8mb4_unicode_ci,
                         `location` point NOT NULL /*!80003 SRID 4326 */,
                         `min_price` int DEFAULT NULL,
                         `parking_guide` text COLLATE utf8mb4_unicode_ci,
                         `payment_notice` text COLLATE utf8mb4_unicode_ci,
                         `phone` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                         `pickup_time_guide` text COLLATE utf8mb4_unicode_ci,
                         `precaution_notice` text COLLATE utf8mb4_unicode_ci,
                         `prepayment` int DEFAULT NULL,
                         `registration_image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `shop_image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `shop_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                         `status` enum('ACTIVE','DELETED','HIDDEN') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `verification_status` enum('NOT_SUBMITTED','REJECTED','VERIFIED') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `owner_id` bigint NOT NULL,
                         PRIMARY KEY (`shop_id`),
                         KEY `FKrduswa89ayj0poad3l70nag19` (`owner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `user_withdrawal` (
                                   `withdrawal_id` bigint NOT NULL AUTO_INCREMENT,
                                   `created_at` datetime(6) NOT NULL,
                                   `updated_at` datetime(6) NOT NULL,
                                   `feedback` text COLLATE utf8mb4_unicode_ci,
                                   `user_id` bigint DEFAULT NULL,
                                   PRIMARY KEY (`withdrawal_id`),
                                   UNIQUE KEY `UKdrgaqg9erfd6yv5aexf7ie86o` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `users` (
                         `user_id` bigint NOT NULL AUTO_INCREMENT,
                         `created_at` datetime(6) NOT NULL,
                         `updated_at` datetime(6) NOT NULL,
                         `deleted_at` datetime(6) DEFAULT NULL,
                         `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                         `kakao_id` bigint NOT NULL,
                         `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `nickname` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
                         birthdate VARCHAR(7) NULL,
                         `phone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                         `profile_image_url` text COLLATE utf8mb4_unicode_ci,
                         `status` enum('ACTIVE','BLOCK','WITHDRAWN') COLLATE utf8mb4_unicode_ci NOT NULL,
                         PRIMARY KEY (`user_id`),
                         UNIQUE KEY `UK6dotkott2kjsp8vw4d0m25fb7` (`email`),
                         UNIQUE KEY `UKk4ycaj27putgcujmehwbsrmmc` (`kakao_id`),
                         UNIQUE KEY `UK2ty1xmrrgtn89xt7kyxx6ta7h` (`nickname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `withdrawal_reason_item` (
                                          `id` bigint NOT NULL AUTO_INCREMENT,
                                          `reason_type` enum('APP_ERROR','EXPENSIVE_PRICE','INCONVENIENT_SERVICE','LACK_OF_DESIGN','NOT_USED_OFTEN','OTHER') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
                                          `withdrawal_id` bigint DEFAULT NULL,
                                          PRIMARY KEY (`id`),
                                          KEY `FKikld4gff84nlgmg3kw6eo65sm` (`withdrawal_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ------------------------------------------------------
-- Foreign Keys
-- ------------------------------------------------------
ALTER TABLE `bank_accounts` ADD CONSTRAINT `FKt6t7oiuxdwfcu798ik0kmkcb2` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `chat_messages` ADD CONSTRAINT `FKgiqeap8ays4lf684x7m0r2729` FOREIGN KEY (`sender_id`) REFERENCES `users` (`user_id`);
ALTER TABLE `chat_messages` ADD CONSTRAINT `FKhalwepod3944695ji0suwoqb9` FOREIGN KEY (`room_id`) REFERENCES `chat_rooms` (`chat_room_id`);
ALTER TABLE `chat_rooms` ADD CONSTRAINT `FK42l1eff8qlbln1331stm3ml2h` FOREIGN KEY (`customer_id`) REFERENCES `users` (`user_id`);
ALTER TABLE `chat_rooms` ADD CONSTRAINT `FKtqhifsbloj4e5rlyobaljrx3f` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `custom_options` ADD CONSTRAINT `FKrugbtewrcp0p4u6d935gtphmc` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `design_options` ADD CONSTRAINT `FKmohfd3bekh421w305mehsfxj` FOREIGN KEY (`design_id`) REFERENCES `design_gallery` (`id`);
ALTER TABLE `favorite_shops` ADD CONSTRAINT `FK7m5h5jy7wn8pqae5hhbhnipgb` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `favorite_shops` ADD CONSTRAINT `FKec6hcwwd5t15ojqqcoyfp1q3h` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`);
ALTER TABLE `order_draft_items` ADD CONSTRAINT `FKih52bdbg2e9tdofv6hvif54gl` FOREIGN KEY (`draft_id`) REFERENCES `orders_drafts` (`id`);
ALTER TABLE `order_draft_items` ADD CONSTRAINT `FKq82jflsxitmkpt4yshjhhh3m9` FOREIGN KEY (`custom_option_id`) REFERENCES `custom_options` (`id`);
ALTER TABLE `order_items` ADD CONSTRAINT `FKbioxgbv59vetrxe0ejfubep1w` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`);
ALTER TABLE `orders` ADD CONSTRAINT `FK21gttsw5evi5bbsvleui69d7r` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `orders` ADD CONSTRAINT `FK32ql8ubntj5uh44ph9659tiih` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`);
ALTER TABLE `orders` ADD CONSTRAINT `FK48bqo75cycyxtwdef0sbxcx7d` FOREIGN KEY (`shop_cake_size_id`) REFERENCES `shop_cake_sizes` (`size_id`);
ALTER TABLE `orders` ADD CONSTRAINT `FKiskguoio3bb0nlsy61lwxh7ub` FOREIGN KEY (`design_id`) REFERENCES `design_gallery` (`id`);
ALTER TABLE `orders_drafts` ADD CONSTRAINT `FK21vvd0w6ny4ndl4sj0yhuggud` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `orders_drafts` ADD CONSTRAINT `FK7pv0b7rtxy4aa8pfg9olib9oc` FOREIGN KEY (`shop_cake_size_id`) REFERENCES `shop_cake_sizes` (`size_id`);
ALTER TABLE `orders_drafts` ADD CONSTRAINT `FK91tsaqqk9uu8mf5ytymh9qrh1` FOREIGN KEY (`design_id`) REFERENCES `design_gallery` (`id`);
ALTER TABLE `orders_drafts` ADD CONSTRAINT `FK9b49wh3mdp87r06briy66omq6` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`);
ALTER TABLE `payments` ADD CONSTRAINT `FK81gagumt0r8y3rmudcgpbk42l` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`);
ALTER TABLE `report` ADD CONSTRAINT `FKqbhdxqd3ly7fkhly5nrl2j93k` FOREIGN KEY (`reporter_id`) REFERENCES `users` (`user_id`);
ALTER TABLE `review_image` ADD CONSTRAINT `FK16wp089tx9nm0obc217gvdd6l` FOREIGN KEY (`review_id`) REFERENCES `review` (`id`);
ALTER TABLE `review_like` ADD CONSTRAINT `FK68am9vk1s1e8n1v873meqkk0k` FOREIGN KEY (`review_id`) REFERENCES `review` (`id`);
ALTER TABLE `review_reply` ADD CONSTRAINT `FK3mfomicwiqwm49ahq8yevep7x` FOREIGN KEY (`review_id`) REFERENCES `review` (`id`);
ALTER TABLE `review_selected_keyword` ADD CONSTRAINT `FK62c7uliqny1qxnhvde152141b` FOREIGN KEY (`keyword_id`) REFERENCES `review_keyword` (`id`);
ALTER TABLE `review_selected_keyword` ADD CONSTRAINT `FKlpkl90lwtqrvm1fyfuolcwb2u` FOREIGN KEY (`review_id`) REFERENCES `review` (`id`);
ALTER TABLE `shop_business_hours` ADD CONSTRAINT `FKdktm12aap5yf6c8tmj68dqfkq` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `shop_cake_sizes` ADD CONSTRAINT `FKsid6g9usj0bjhh7k5sxcnsvto` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `shop_events` ADD CONSTRAINT `FKt7qu2wqs1y53ofhd9ps8h9s0d` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `shop_keyword_mapping` ADD CONSTRAINT `FK32jsqya1i9t0bx9lw99vfftks` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`shop_id`);
ALTER TABLE `shop_keyword_mapping` ADD CONSTRAINT `FK8l02mxoj8alsu70ek4flx9mdf` FOREIGN KEY (`keyword_id`) REFERENCES `shop_appeal_keywords` (`keyword_id`);
ALTER TABLE `shops` ADD CONSTRAINT `FKrduswa89ayj0poad3l70nag19` FOREIGN KEY (`owner_id`) REFERENCES `users` (`user_id`);
ALTER TABLE `user_withdrawal` ADD CONSTRAINT `FK8k107oerpjjbjjcvb3dp5r802` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`);
ALTER TABLE `withdrawal_reason_item` ADD CONSTRAINT `FKikld4gff84nlgmg3kw6eo65sm` FOREIGN KEY (`withdrawal_id`) REFERENCES `user_withdrawal` (`withdrawal_id`);
ALTER TABLE `design_options` ADD CONSTRAINT `fk_design_options_custom_option_id` FOREIGN KEY (`custom_option_id`) REFERENCES `custom_options` (`id`);
ALTER TABLE `order_items` ADD CONSTRAINT `fk_order_items_custom_option_id` FOREIGN KEY (`custom_option_id`) REFERENCES `custom_options` (`id`);

SET FOREIGN_KEY_CHECKS = 1;
